### ISSUE TITLE
footer has a dark background even with light theme 

### ISSUE THREAD

**Issue by ghost** [Spectralitree/pk-webs-svelte#1]
![h](https://user-images.githubusercontent.com/64013111/147405362-598896fc-276a-4b1b-a519-582232aab91c.png)

**Comment by Draconizations** [comment]
this _is_ intentional, but I can see how it is confusing. I'll have to decide (or let the community help decide) whether to keep it or not

**Comment by Draconizations** [comment]
this has been changed in recent commits! thanks for reporting :)
